# Generated by Django 5.1.3 on 2024-12-11 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0002_option_covoiturage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='covoiturage',
            name='time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
    ]
