# Generated by Django 5.1.3 on 2024-12-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0003_covoiturage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covoiturage',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
