# Generated by Django 5.1.3 on 2024-12-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0004_alter_covoiturage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covoiturage',
            name='addresses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
