# Generated by Django 5.1.3 on 2024-11-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
