# Generated by Django 5.1.3 on 2024-12-04 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car_picture',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='cartype',
        ),
        migrations.AddField(
            model_name='driver',
            name='bio',
            field=models.TextField(blank=True, default="This driver didn't add a bio", max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('cartype', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('CONVERTIBLE', 'Convertible'), ('COUPE', 'Coupe'), ('WAGON', 'Wagon'), ('PICKUP', 'Pickup'), ('MINIVAN', 'Minivan'), ('SPORTS', 'Sports Car'), ('ELECTRIC', 'Electric Car')], default='SEDAN', max_length=50)),
                ('car_picture', models.ImageField(blank=True, null=True, upload_to='car_pictures/')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='core.driver')),
            ],
        ),
    ]
